### ISSUE TITLE
!support request not pinging member

### ISSUE THREAD

**Issue by Penecruz** [ozdeadmeat/DDC2#14] opened 2021-04-27 02:40 UTC
The !support request is responding however only the nominated members discord ID is being written and no mention is being recorded in Discord, User is nominated and set to TRUE.

**Comment by ozdeadmeat** [comment] 2021-04-28 11:10
The Discord ID was only being mentioned in the Support channel. This is done by design as to prompt the support person to look at the support channel in the event that your Discord Server has disabled the ability for members to mention people by name. 

There was an issue with the ID being displayed correctly in the  support channel and this has been fixed and will be part of the next update.

**Comment by ozdeadmeat** [comment] 2021-04-29 16:21
current work around to get this working is to put information into string like this "<@USERID>". As mentioned earlier, this will be resolved in the next release of DDC2

**Comment by ozdeadmeat** [comment] 2021-05-04 04:53
Fix found and applied to next version of DDC2. (v2.0j)

Will only ping support staff if request is in support channel.

**Closed as completed by ozdeadmeat** 2021-05-04 04:53 UTC
